#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Automatically Start X after login to Virtual Terminal
[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
