#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export XDG_CONFIG_HOME=$HOME/.config
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
export LESSOPEN='|pygmentize %s'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

export GOPATH="$HOME/Documents/programming/gows"

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
cdpath=(
  $HOME
  $HOME/Documents/programming
  $cdpath
)

# Set the list of directories that autoload searches.
fpath=(
  ${ZDOTDIR:-$HOME}/customs/funcs
  $fpath
)

# Set the list of directories that Zsh searches for programs.
path=(
# local path
  $HOME/.local/bin                               # User local script
  $HOME/.local/opt
  $HOME/.gem/ruby/2.3.0/bin
  /usr/local/{bin,sbin}                          # System local script

# system path
  $GOPATH/bin                                    # Go
  /opt						 # opt
  /usr/lib/jvm/default/include                   # JVM include files
  $path
)

#
# Named Directories
#

hash -d programming="$HOME/Documents/programming"
hash -d zsh="${ZDOTDIR:-$HOME}"
hash -d zprezto="${ZDOTDIR:-$HOME}/.zprezto"

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-i -M -R -w -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

#
# Java environment variables
#

export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
export _JAVA_AWT_WM_NONREPARENTING=1

#
# GPG
#

GPG_TTY=$(tty)
export GPG_TTY
