#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

rcdir="${ZDOTDIR:-$HOME}"
# Source Prezto.
if [[ -s "$rcdir/init.zsh" ]]; then
  source "$rcdir/init.zsh"
fi

# Customize to your needs...
# additional path
path=(
  $HOME/bin                           # User local script
  $HOME/.local/{bin,opt}              # User local script
  $GOPATH/bin                         # Go
  /opt                                # opt
  /usr/lib/jvm/default/include        # JVM include files
  $path
)


# module options override
setopt clobber
export KEYTIMEOUT=1

# load custom functions
fpath=(
  ${ZDOTDIR:-$HOME}/funcs
  $fpath
)
autoload -Uz "${fpath[1]}"/*(.:t)

# source user configurations
for file ("$rcdir/customs"/*.zsh(.))
    if [[ -a "$file" ]]; then
        source "$file"
    fi
unset file
unset sources
