#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

rcdir="${ZDOTDIR:-$HOME}"
# Source Prezto.
if [[ -s "$rcdir/init.zsh" ]]; then
  source "$rcdir/init.zsh"
fi

# Customize to your needs...

# module options override
setopt clobber
export KEYTIMEOUT=1

# load custom functions
fpath=(
  ${ZDOTDIR:-$HOME}/funcs
  $fpath
)
autoload -Uz "${fpath[1]}"/*(.:t)

# source user configurations
for file ("$rcdir/customs"/*.zsh(.))
    if [[ -a "$file" ]]; then
        source "$file"
    fi
unset file
unset sources

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
